openapi: 3.0.3
info:
  title: Schema del Datore di Lavoro Domestico
  version: 202301.10.00
  x-summary: Schema del Datore di Lavoro Domestico compatibile con l'Ontologia INPS relativa a Riscatti, Ricongiunzioni, Rendite e Lavoratore Domestico
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Rappresenta il titolare di un rapporto di lavoro con un lavoratore domestico. Solitamente è una persona fisica ma, in alcuni casi particolari, può essere un'organizzazione qualora quest'ultima si configuri come una comunità stabile o una convivenza familiarmente strutturata senza fini di lucro presso cui il lavoratore svolge servizi domestici tipici della vita familiare.
   La metadatazione semantica degli schemi si basa sul documento
   [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    IdDatoreLavoroDomestico:
      type: string
      description:
        Codice relativo al Rapporto Di Lavoro Domestico, è finalizzato all'individuazione univoca di ogni record dell'entità. Associato a https://w3id.org/italia/onto/OP21/identificatoreDatoreDiLavoroDomestico.
      example: '15463'
      maxLength: 50
      minLength: 1

    DatoreDiLavoroDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/DatoreDiLavoroDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_datore_lavoro_domestico: identificatoreDatoreDiLavoroDomestico
      additionalProperties: true
      description:
         Questo schema rappresenta il titolare di un rapporto di lavoro con un lavoratore domestico.
         Associato a https://w3id.org/italia/onto/OP21/DatoreDiLavoroDomestico.
      required:
      - id_datore_lavoro_domestico
      properties:
        id_datore_lavoro_domestico:
          $ref: "#/components/schemas/IdDatoreLavoroDomestico"
      example:
        id_datore_lavoro_domestico: '15463'