openapi: 3.0.3
info:
  title: Schema del Rapporto di Lavoro Domestico Annullato
  version: 202406.04.00
  x-summary: Schema del Rapporto di Lavoro Domestico Annullato compatibile con l'Ontologia INPS relativa ai contributi previdenziali.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
    https://w3id.org/italia/social-security/onto/domesticWorkServices/RapportoDiLavoroDomesticoAnnullato
paths: {}
servers: []
tags: []
components:
  schemas:
    LavoratoreDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico"
    ContrattoLavoro:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico"
    DatoreDiLavoroDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico"

    IdRapportoLavoroDomesticoAnnullato:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      description: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      example: '175923'
      maxLength: 50
      minLength: 1

    RapportoLavoroDomesticoAnnullato:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/domesticWorkServices/RapportoDiLavoroDomesticoAnnullato
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/domesticWorkServices/"
        data_presentazione_annullamento: dataPresentazioneAnnullamento
        emersione_lavoro_irregolare_rapporto_annullato: emersioneLavoroIrregolare
        annullato_da_datore_di_lavoro_domestico: annullatoDa
        annullato_da_sede_inps: annullatoDa
        annullato_da_delegato: annullatoDa
        rapporto_lavoro_domestico_annullato_ha_stato_precedente:
          "@id": rapportoDiLavoroDomesticoAnnullatoHaStatoPrecedente
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/domesticWorkServices/RapportoDiLavoroDomesticoAnnullato
      required:
      - codice_rapporto_lavoro_annullato
      - data_firma_contratto_rapporto_annullato
      - data_comunicazione_inizio_rapporto_annullato
      - data_presentazione_annullamento
      - emersione_lavoro_irregolare_rapporto_annullato
      properties:
        codice_rapporto_lavoro_annullato:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoAnnullato"
        data_firma_contratto_rapporto_annullato:
          $ref: "#/components/schemas/DataFirmaContrattoRapportoAnnullato"
        data_comunicazione_inizio_rapporto_rapporto_annullato:
          $ref: "#/components/schemas/DataComunicazioneInizioRapportoAnnullato"
        emersione_lavoro_irregolare_rapporto_annullato:
          type: string
          format: boolean
        data_presentazione_annullamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        annullato_da_datore_di_lavoro_domestico:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        annullato_da_sede_inps:
          type: object
          items:
            $ref: "#/components/schemas/SedeINPS"
        annullato_da_delegato:
          type: object
          items:
            $ref: "#/components/schemas/Delegato"
        rapporto_lavoro_domestico_annullato_ha_stato_precedente:
          type: object
          items:
            $ref: "#/components/schemas/RapportoDiLavoroDomesticoIscritto"
        ha_lavoratore_domestico_rapporto_annullato:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro_domestico_rapporto_annullato:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        ha_contratto_di_lavoro_domestico_rapporto_annullato:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro_annullato:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoAnnullato/example"
        data_firma_contratto_rapporto_annullato:
          $ref: "#/components/schemas/DataFirmaContrattoRapportoAnnullato/example"
        data_comunicazione_inizio_rapporto_annullato:
          $ref: "#/components/schemas/DataComunicazioneInizioRapportoAnnullato/example"
        data_presentazione_annullamento: '2022-06-15'
        emersione_lavoro_irregolare_rapporto_annullato: 'false'
        annullato_da_datore_di_lavoro_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        annullato_da_sede_inps:
          $ref: "#/components/schemas/SedeINPS/example"
        annullato_da_delegato:
          $ref: "#/components/schemas/Delegato/example"
        rapporto_lavoro_domestico_annullato_ha_stato_precedente:
          $ref: "#/components/schemas/RapportoDiLavoroDomesticoIscritto/example"
        ha_lavoratore_domestico_rapporto_annullato:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro_domestico_rapporto_annullato:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        ha_contratto_di_lavoro_domestico_rapporto_annullato:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico/example"

    DataComunicazioneInizioRapportoAnnullato:
      type: string
      format: date
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/dataComunicazioneInizioRapporto
      description: https://w3id.org/italia/social-security/onto/contributions/dataComunicazioneInizioRapporto
      example: '2022-06-20'
      maxLength: 50
      minLength: 1

    DataFirmaContrattoRapportoAnnullato:
      type: string
      format: date
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/dataFirmaContratto
      description: https://w3id.org/italia/social-security/onto/contributions/dataFirmaContratto
      example: '2022-06-10'
      maxLength: 50
      minLength: 1

    RapportoDiLavoroDomesticoIscritto:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/domesticWorkServices/RapportoDiLavoroDomesticoIscritto
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/domesticWorkServices/"
        emersione_lavoro_irregolare_rapporto_iscritto: emersioneLavoroIrregolare
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/domesticWorkServices/RapportoDiLavoroDomesticoIscritto
      required:
      - codice_rapporto_lavoro_iscritto
      - data_firma_contratto_rapporto_iscritto
      - data_comunicazione_inizio_rapporto_iscritto
      - emersione_lavoro_irregolare_rapporto_iscritto
      properties:
        codice_rapporto_lavoro_iscritto:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoIscritto"
        data_firma_contratto_rapporto_iscritto:
          $ref: "#/components/schemas/DataFirmaContrattoRapportoIscritto"
        data_comunicazione_inizio_rapporto_iscritto:
          $ref: "#/components/schemas/DataComunicazioneInizioRapportoIscritto"
        emersione_lavoro_irregolare_rapporto_iscritto:
          type: string
          format: boolean
        ha_lavoratore_domestico_rapporto_iscritto:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro_domestico_rapporto_iscritto:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        ha_contratto_di_lavoro_domestico_rapporto_iscritto:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro_iscritto:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoIscritto/example"
        data_firma_contratto_rapporto_iscritto:
          $ref: "#/components/schemas/DataComunicazioneInizioRapportoIscritto/example"
        data_comunicazione_inizio_rapporto_iscritto:
          $ref: "#/components/schemas/DataComunicazioneInizioRapportoIscritto/example"
        emersione_lavoro_irregolare_rapporto_iscritto: 'false'
        ha_lavoratore_domestico_rapporto_iscritto:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro_domestico_rapporto_iscritto:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        ha_contratto_di_lavoro_domestico_rapporto_iscritto:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico/example"


    IdRapportoLavoroDomesticoIscritto:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      description: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      example: '175923'
      maxLength: 50
      minLength: 1

    DataComunicazioneInizioRapportoIscritto:
      type: string
      format: date
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/dataComunicazioneInizioRapporto
      description: https://w3id.org/italia/social-security/onto/contributions/dataComunicazioneInizioRapporto
      example: '2022-06-20'
      maxLength: 50
      minLength: 1

    DataFirmaContrattoRapportoIscritto:
      type: string
      format: date
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/dataFirmaContratto
      description: https://w3id.org/italia/social-security/onto/contributions/dataFirmaContratto
      example: '2022-06-10'
      maxLength: 50
      minLength: 1

    SedeINPS:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/core/SedeINPS
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/core/"
        denominazione_sede_inps: denominazioneSedeINPS
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/core/SedeINPS
      required:
      - codice_sede_inps
      - denominazione_sede_inps
      properties:
        codice_sede_inps:
          $ref: "#/components/schemas/CodiceSedeINPS"
        denominazione_sede_inps:
          type: string
          maxLength: 255
      example:
        codice_sede_inps:
          $ref: "#/components/schemas/CodiceSedeINPS/example"
        denominazione_sede_inps: "INPS Roma Tuscolano"

    CodiceSedeINPS:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/core/codiceSedeINPS
      description: https://w3id.org/italia/social-security/onto/core/codiceSedeINPS
      example: '1985675'
      maxLength: 50
      minLength: 1

    Delegato:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/relevantLegislation/Delegato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/relevantLegislation/"
        denominazione_delegato: denominazioneDelegato
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/relevantLegislation/Delegato
      required:
      - codice_delegato
      - denominazione_delegato
      properties:
        codice_delegato:
          $ref: "#/components/schemas/CodiceDelegato"
        denominazione_delegato:
          type: string
          maxLength: 255
      example:
        codice_delegato:
          $ref: "#/components/schemas/CodiceDelegato/example"
        denominazione_delegato: "Centro Servizi Caf Tuscolano"

    CodiceDelegato:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/relevantLegislation/codiceDelegato
      description: https://w3id.org/italia/social-security/onto/relevantLegislation/codiceDelegato
      example: '14857952'
      maxLength: 50
      minLength: 1