openapi: 3.0.3
info:
  title: Schema del Rapporto di Lavoro Domestico Attivo
  version: 202406.04.00
  x-summary: Schema del Rapporto di Lavoro Domestico Attivo compatibile con l'Ontologia INPS relativa ai contributi previdenziali.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
    https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomesticoAttivo
paths: {}
servers: []
tags: []
components:
  schemas:
    LavoratoreDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico"
    ContrattoLavoro:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico"
    DatoreDiLavoroDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico"

    IdRapportoLavoroDomesticoAttivo:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      description: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      example: '152486'
      maxLength: 50
      minLength: 1

    RapportoDiLavoroDomesticoAttivo:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomesticoAttivo
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/contributions/"
        data_firma_contratto_rapporto_attivo: dataFirmaContratto
        data_comunicazione_inizio_rapporto_attivo: dataComunicazioneInizioRapporto
        ha_lavoratore_domestico_rapporto_attivo:
          "@id": haLavoratoreDomestico
        ha_datore_di_lavoro_domestico_rapporto_attivo:
          "@id": haDatoreDiLavoroDomestico
        ha_contratto_di_lavoro_domestico_rapporto_attivo:
          "@id": haContrattoDiLavoroDomestico
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomesticoAttivo
      required:
      - codice_rapporto_lavoro_attivo
      - data_firma_contratto_rapporto_attivo
      - data_comunicazione_inizio_rapporto_attivo
      - data_inizio_rapporto_lavoro_domestico_attivo
      properties:
        codice_rapporto_lavoro_attivo:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoAttivo"
        data_firma_contratto_rapporto_attivo:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_comunicazione_inizio_rapporto_attivo:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        data_inizio_rapporto_lavoro_domestico_attivo:
          $ref: "#/components/schemas/DataInizioRapportoLavoroDomesticoAttivo"
        ha_lavoratore_domestico_rapporto_attivo:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro_domestico_rapporto_attivo:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        ha_contratto_di_lavoro_domestico_rapporto_attivo:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro_attivo:
          $ref: "#/components/schemas/IdRapportoLavoroDomesticoAttivo/example"
        data_firma_contratto_rapporto_attivo: '2023-04-12'
        data_comunicazione_inizio_rapporto_attivo: '2023-05-01'
        data_inizio_rapporto_lavoro_domestico_attivo: '2023-05-03'
        ha_lavoratore_domestico_rapporto_attivo:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro_domestico_rapporto_attivo:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        ha_contratto_di_lavoro_domestico_rapporto_attivo:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico/example"

    DataInizioRapportoLavoroDomesticoAttivo:
      type: string
      format: date
      pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      x-refersTo: https://w3id.org/italia/social-security/onto/domesticWorkServices/dataInizioRapportoLavoroAttivo
      description: https://w3id.org/italia/social-security/onto/domesticWorkServices/dataInizioRapportoLavoroAttivo
      example: '2025-07-15'
      maxLength: 50
      minLength: 1