openapi: 3.0.3
info:
  title: Schema dell'Ordine di Pagamento
  version: 202401.18.00
  x-summary: Schema dell'ordine di pagamento compatibile con l'Ontologia INPS relativa a servizi che rivestono uno stesso ruolo nell'ambito di diversi processi produttivi dell'Istituto.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: https://w3id.org/italia/social-security/onto/services/OrdineDiPagamento
paths: {}
servers: []
tags: []
components:
  schemas:

    IdOrdinePagamento:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/services/identificatoreOrdinePagamento
      description: https://w3id.org/italia/social-security/onto/services/identificatoreOrdinePagamento
      example: '987654321'
      maxLength: 50
      minLength: 1

    OrdinePagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/OrdineDiPagamento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        data_ordine_pagamento: dataOrdinePagamento
        esegue_accredito:
          "@id": esegueAccredito
        esegue_addebito:
          "@id": esegueAddebito
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/OrdineDiPagamento
      required:
      - codice_ordine_pagamento
      - data_ordine_pagamento
      properties:
        codice_ordine_pagamento:
          $ref: "#/components/schemas/IdOrdinePagamento"
        data_ordine_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        esegue_accredito:
          type: object
          items:
            $ref: "#/components/schemas/MovimentoDiDenaro"
        esegue_addebito:
          type: object
          items:
            $ref: "#/components/schemas/MovimentoDiDenaro"
      example:
        codice_ordine_pagamento:
          $ref: "#/components/schemas/IdOrdinePagamento/example"
        data_ordine_pagamento: '2022-06-30'
        esegue_accredito:
          $ref: "#/components/schemas/MovimentoDiDenaro/example"
        esegue_addebito:
          $ref: "#/components/schemas/MovimentoDiDenaro/example"

    MovimentoDiDenaro:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/MovimentoDiDenaro
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        id_movimento: identificatoreMovimento
        causale_movimento: causaleMovimento
        importo_movimento: importoMovimento
        importo_commissione_movimento: importoCommissioneMovimento
        data_movimento: dataMovimento
        invia_ricevuta_movimento:
          "@id": inviaRicevutaDiMovimento
        movimento_agisce_su:
          "@id": movimentoAgisceSu
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/MovimentoDiDenaro
      required:
      - id_movimento
      - causale_movimento
      - importo_movimento
      - importo_commissione_movimento
      - data_movimento
      properties:
        id_movimento:
          type: string
          maxLength: 50
        causale_movimento:
          type: string
          maxLength: 255
        importo_movimento:
          type: number
          format: double
        importo_commissione_movimento:
          type: number
          format: double
        data_movimento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        invia_ricevuta_movimento:
          type: object
          items:
            $ref: "#/components/schemas/RicevutaDiMovimento"
        movimento_agisce_su:
          type: object
          items:
            $ref: "#/components/schemas/ContoCorrente"
      example:
        id_movimento: '154864'
        causale_movimento: 'Pagamento'
        importo_movimento: 500.50
        importo_commissione_movimento: 2.50
        data_movimento: '2022-07-14'
        invia_ricevuta_movimento:
          $ref: "#/components/schemas/RicevutaDiMovimento/example"
        movimento_agisce_su:
          $ref: "#/components/schemas/ContoCorrente/example"

    RicevutaDiMovimento:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/RicevutaDiMovimento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        id_ricevuta_accredito: identificatoreRicevuta
        data_ricevuta: dataRicevuta
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/RicevutaDiMovimento
      required:
      - id_ricevuta_accredito
      - data_ricevuta
      properties:
        id_ricevuta_accredito:
          type: string
          maxLength: 50
        data_ricevuta:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
      example:
        id_ricevuta_accredito: '123546'
        data_ricevuta: '2022-07-25'

    ContoCorrente:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/ContoCorrente
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        iban: IBAN
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/ContoCorrente
      required:
      - iban
      properties:
        iban:
          type: string
          maxLength: 50
      example:
        iban: 'IT 99 C 12345 67890 123456789012'
