openapi: 3.0.3
info:
  title: Schema della Domanda Rilascio Modello A1
  version: 202403.07.00
  x-summary: Schema della Domanda Rilascio Modello A1 compatibile con l'Ontologia INPS relativa alla Legislazione Pertinente
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: https://w3id.org/italia/social-security/onto/relevantLegislation/DomandaRilascioModelloA1
paths: {}
servers: []
tags: []
components:
  schemas:

    IdDomandaRilascioModelloA1:
      type: string
      description: https://w3id.org/italia/social-security/onto/relevantLegislation/codiceDomandaRilascioModelloA1
      example: '0238'
      maxLength: 50
      minLength: 1

    DomandaRilascioModelloA1:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/relevantLegislation/DomandaRilascioModelloA1
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/relevantLegislation/"
        codice_domanda_rilascio_modello_a1: codiceDomandaRilascioModelloA1
        domanda_ha_dichiarazione:
          "@id": domandaHaDichiarazione
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/relevantLegislation/DomandaRilascioModelloA1
      required:
      - codice_domanda_rilascio_modello_a1
      properties:
        codice_domanda_rilascio_modello_a1:
          $ref: "#/components/schemas/IdDomandaRilascioModelloA1"
        domanda_ha_dichiarazione:
          type: object
          items:
            $ref: "#/components/schemas/Dichiarazione"
      example:
        codice_domanda_rilascio_modello_a1: '0238'
        domanda_ha_dichiarazione:
          $ref: "#/components/schemas/Dichiarazione/example"

    Dichiarazione:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/relevantLegislation/Dichiarazione
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/relevantLegislation/"
        valore_dichiarazione: valoreDichiarazione
        descrizione_dichiarazione: descrizioneDichiarazione
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/relevantLegislation/Dichiarazione
      required:
      - valore_dichiarazione
      - descrizione_dichiarazione
      properties:
        valore_dichiarazione:
          type: string
          maxLength: 50
        descrizione_dichiarazione:
          type: string
          maxLength: 255
      example:
        valore_dichiarazione: '1'
        descrizione_dichiarazione: 'Dichiaro che al termine del periodo di distacco, continuerò a svolgere la mia attività in Italia'