openapi: 3.0.3
info:
  title: Schema del Rapporto di Lavoro Domestico
  version: 202401.18.00
  x-summary: Schema del Rapporto di Lavoro Domestico compatibile con l'Ontologia INPS relativa ai contributi previdenziali.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Rapporto di lavoro tra un datore di lavoro e un lavoratore subordinato che presta servizi di carattere domestico diretti al funzionamento della vita familiare. È fatto obbligo al datore di lavoro di comunicare all'INPS l'istaurarsi di tale rapporto di lavoro, prima della data di assunzione, così come qualsiasi modifica dei termini del rapporto stesso ovvero la sua cessazione. In virtù di tale comunicazione, al rapporto di lavoro viene assegnato da INPS un codice identificativo utile per qualsiasi successivo adempimento inerente al rapporto stesso. Il contratto può modificarsi nel tempo quindi a ciascuna istanza è associato un intervallo di validità (sottoclasse di TI:TimeIndexedEvent).
   La metadatazione semantica degli schemi si basa sul documento
   [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    LavoratoreDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico"
    ContrattoLavoro:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico"
    DatoreDiLavoroDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico"

    IdRapportoLavoroDomestico:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      description:
        Codice relativo al Rapporto Di Lavoro Domestico assegnato da INPS al momento della registrazione del relativo contratto ed è finalizzato all'individuazione univoca di ogni record dell'entità. Associato a https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro.
      example: '789431'
      maxLength: 50
      minLength: 1

    RapportoLavoroDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/contributions/"
        data_firma_contratto: dataFirmaContratto
        ha_lavoratore_domestico:
          "@id": haLavoratoreDomestico
        ha_datore_di_lavoro_domestico:
          "@id": haDatoreDiLavoroDomestico
        ha_contratto_di_lavoro_domestico:
          "@id": haContrattoDiLavoroDomestico
      additionalProperties: true
      description:
         Questo schema rappresenta un rapporto di lavoro tra un datore di lavoro e un lavoratore subordinato che presta servizi di carattere domestico diretti al funzionamento della vita familiare.
         Associato ad https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomestico.
      required:
      - codice_rapporto_lavoro
      - data_firma_contratto
      properties:
        codice_rapporto_lavoro:
          $ref: "#/components/schemas/IdRapportoLavoroDomestico"
        data_firma_contratto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        ha_lavoratore_domestico:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro_domestico:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        ha_contratto_di_lavoro_domestico:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro:
          $ref: "#/components/schemas/IdRapportoLavoroDomestico/example"
        data_firma_contratto: '2023-02-16'
        ha_lavoratore_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        ha_contratto_di_lavoro_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro/latest/contratto-di-lavoro.oas3.yaml#/components/schemas/ContrattoLavoro/example"
