openapi: 3.0.3
info:
  title: Schema del Lavoratore Domestico
  version: 202301.10.00
  x-summary: Schema del Lavoratore Domestico compatibile con l'Ontologia INPS relativa a Riscatti, Ricongiunzioni, Rendite e Lavoratore Domestico
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Rappresenta colui che svolge mansioni e prestazioni di servizi domestici diretti al funzionamento della vita familiare nell'ambito di una residenza. I lavoratori domestici svolgono quindi una varietà di servizi rivolti ad un individuo e/o ad una comunità, dalla pulizia e manutenzione della casa, alla cucina, al bucato e alla stiratura, alla cura dei bambini e degli anziani a carico e ad altre commissioni domestiche. Ciascuna istanza possiede un identificatore.
   La metadatazione semantica degli schemi si basa sul documento
   [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    IdLavoratoreDomestico:
      type: string
      description:
        Identificativo relativo al Lavoratore Domestico, è finalizzato all'individuazione univoca di ogni record dell'entità ed è associato a https://w3id.org/italia/onto/OP21/identificatoreLavoratoreDomestico.
      example: '216879'
      maxLength: 50
      minLength: 1

    LavoratoreDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/LavoratoreDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_lavoratore_domestico: identificatoreLavoratoreDomestico
      additionalProperties: true
      description:
         Questo schema rappresenta un lavoratore che svolge mansioni e prestazioni di servizi domestici diretti al funzionamento della vita familiare nell'ambito di una residenza. È associato a https://w3id.org/italia/onto/OP21/LavoratoreDomestico.
      required:
      - id_lavoratore_domestico
      properties:
        id_lavoratore_domestico:
          $ref: "#/components/schemas/IdLavoratoreDomestico"
      example:
        id_lavoratore_domestico: '216879'
