openapi: 3.0.3
info:
  title: Schema del Mandato SDD
  version: 202401.18.00
  x-summary: Schema del Mandato Sepa Direct Debit (SDD) compatibile con l'Ontologia INPS relativa a servizi che rivestono uno stesso ruolo nell'ambito di diversi processi produttivi dell'Istituto.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   https://w3id.org/italia/social-security/onto/services/MandatoSDD
paths: {}
servers: []
tags: []
components:
  schemas:

    CodiceMandato:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/services/codiceMandato
      description: https://w3id.org/italia/social-security/onto/services/codiceMandato
      example: '78976'
      maxLength: 50
      minLength: 1

    MandatoSdd:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/MandatoSDD
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        addebito_ricorrente: addebitoRicorrente
        ha_creditore_mandato:
          "@id": haCreditoreMandato
        ha_debitore_mandato:
          "@id": haDebitoreMandato
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/services/MandatoSDD
      required:
      - codice_mandato
      - addebito_ricorrente
      properties:
        codice_mandato:
          $ref: "#/components/schemas/CodiceMandato"
        addebito_ricorrente:
          type: string
          maxLength: 255
        ha_creditore_mandato:
          type: object
          items:
            $ref: "#/components/schemas/CreditoreMandato"
        ha_debitore_mandato:
          type: object
          items:
            $ref: "#/components/schemas/DebitoreMandato"
      example:
        codice_mandato:
          $ref: "#/components/schemas/CodiceMandato/example"
        addebito_ricorrente: 'True'
        ha_creditore_mandato:
          $ref: "#/components/schemas/CreditoreMandato/example"
        ha_debitore_mandato:
          $ref: "#/components/schemas/DebitoreMandato/example"

    CreditoreMandato:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/CreditoreMandato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        id_creditore_mandato: identificatoreCorrentista
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/CreditoreMandato
      required:
      - id_creditore_mandato
      properties:
        id_creditore_mandato:
          type: string
          maxLength: 50
      example:
        id_creditore_mandato: '654321'

    DebitoreMandato:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/DebitoreMandato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        id_debitore_mandato: identificatoreCorrentista
      additionalProperties: true
      description:
          https://w3id.org/italia/social-security/onto/services/DebitoreMandato
      required:
      - id_debitore_mandato
      properties:
        id_debitore_mandato:
          type: string
          maxLength: 50
      example:
        id_debitore_mandato: '123456'