openapi: 3.0.3
info:
  title: Schema del Mandato SDD
  version: 202301.10.00
  x-summary: Schema del Mandato Sepa Direct Debit (SDD) compatibile con l'Ontologia INPS relativa a Riscatti, Ricongiunzioni, Rendite e Lavoratore Domestico.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Il Mandato SDD (Sepa Direct Debit) è uno strumento d'incasso preautorizzato utilizzato all'interno di paesi dell'area SEPA con scadenze e importi predeterminati.
   È caratterizzato da un codice identificativo e dalla possibilità di indicare se trattasi di un pagamento ricorrente o unico.
   Al mandato sono necessariamente legati il soggetto creditore e il soggetto debitore mediante l'indicazione dei rispettivi IBAN.
   La metadatazione semantica degli schemi si basa sul documento
   [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:

    CodiceMandato:
      type: string
      description:
        Campo tecnico finalizzato all'individuazione univoca di ogni record del Mandato SDD.
        Associato a https://w3id.org/italia/onto/OP21/codiceMandato.
      example: '78976'
      maxLength: 50
      minLength: 1

    MandatoSdd:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/MandatoSDD
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        codice_mandato: codiceMandato
        addebito_ricorrente: addebitoRicorrente
        ha_creditore_mandato:
          "@id": haCreditoreMandato
        ha_pratica_per_mandato:
          "@id": haPraticaPerMandato
        ha_debitore_mandato:
          "@id": haDebitoreMandato
      additionalProperties: true
      description:
         Questo schema rappresenta un mandato sepa direct debit (sdd), strumento d'incasso preautorizzato utilizzato all'interno di paesi dell'area SEPA con scadenze e importi predeterminati.
         È associato ad https://w3id.org/italia/onto/OP21/MandatoSDD.
      required:
      - codice_mandato
      - addebito_ricorrente
      properties:
        codice_mandato:
          $ref: "#/components/schemas/CodiceMandato"
        addebito_ricorrente:
          type: string
          maxLength: 255
        ha_creditore_mandato:
          type: object
          items:
            $ref: "#/components/schemas/CreditoreMandato"
        ha_pratica_per_mandato:
          type: object
          items:
            $ref: "#/components/schemas/PraticaAdeguamentoRateizzata"
        ha_debitore_mandato:
          type: object
          items:
            $ref: "#/components/schemas/DebitoreMandato"
      example:
        codice_mandato: '78976'
        addebito_ricorrente: 'True'
        ha_creditore_mandato:
          id_creditore_mandato: '654321'
        ha_pratica_per_mandato:
          id_pratica_adeguamento: '15646512'
          descrizione_pratica_adeguamento: 'Adeguamento contributivo'
        ha_debitore_mandato:
          id_debitore_mandato: '123456'

    CreditoreMandato:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/CreditoreMandato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_creditore_mandato: identificatoreCorrentista
      additionalProperties: true
      description:
          Questo schema rappresenta il creditore del mandato sdd ed è associato a https://w3id.org/italia/onto/OP21/CreditoreMandato.
      required:
      - id_creditore_mandato
      properties:
        id_creditore_mandato:
          type: string
          maxLength: 50
      example:
        id_creditore_mandato: '654321'

    PraticaAdeguamentoRateizzata:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/PraticaDiAdeguamentoRateizzata
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_pratica_adeguamento: numeroPratica
        descrizione_pratica_adeguamento: descrizionePratica
      additionalProperties: true
      description:
          Questo schema rappresenta una pratica di adeguamento rateizzata, una pratica di adeguamento contributivo in stato di Notificato Importo che è legata ad un piano di ammortamento e come tali prevedono la possibilità di attivare un mandato SDD per il pagamento delle rate.
          Lo schema è associato a https://w3id.org/italia/onto/OP21/PraticaDiAdeguamentoRateizzata.
      required:
      - id_pratica_adeguamento
      - descrizione_pratica_adeguamento
      properties:
        id_pratica_adeguamento:
          type: string
          maxLength: 50
          minLength: 1
        descrizione_pratica_adeguamento:
          type: string
          maxLength: 255
      example:
        id_pratica_adeguamento: '15646512'
        descrizione_pratica_adeguamento: 'Adeguamento contributivo'

    DebitoreMandato:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/DebitoreMandato
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        id_debitore_mandato: identificatoreCorrentista
      additionalProperties: true
      description:
          Questo schema rappresenta il debitore del mandato sdd ed è associato a https://w3id.org/italia/onto/OP21/DebitoreMandato.
      required:
      - id_debitore_mandato
      properties:
        id_debitore_mandato:
          type: string
          maxLength: 50
      example:
        id_debitore_mandato: '123456'