openapi: 3.0.1
info:
  title: Schema API delle Info Pensioni
  description: Schema API delle Info Pensioni relativo all'e-service pubblicato sulla PDND al seguente link https://api.inps.it/pdnd/rest/InfoPensioni/v1
  version: '1.0'
paths: {}
components:
  schemas:
    InfoPensioniVigentiRequest:
      type: object
      properties:
        codiceFiscale:
          type: string
          nullable: true
      x-jsonld-type: https://w3id.org/italia/social-security/onto/pensions/PrestazionePensionistica
      x-jsonld-context:
        "@vocab": https://w3id.org/italia/social-security/onto/pensions/
        codiceFiscale: https://w3id.org/italia/onto/CPV/taxCode
      example:
        codiceFiscale: 'AAAAAA00A00A000A'
      additionalProperties: false
    InfoPensioniVigentiResponse:
      type: object
      properties:
        messaggio:
          type: string
          nullable: true
        esecuzione:
          type: boolean
        presenzaPensioniVigenti:
          type: boolean
      additionalProperties: false
    Problem:
      type: object
      properties:
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties: false