openapi: 3.0.3
info:
  title: Schema del Rapporto di Lavoro Domestico
  version: 202301.10.00
  x-summary: Schema del Rapporto di Lavoro Domestico compatibile con l'Ontologia INPS relativa a Riscatti, Ricongiunzioni, Rendite e Lavoratore Domestico
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Rapporto di lavoro tra un datore di lavoro e un lavoratore subordinato che presta servizi di carattere domestico diretti al funzionamento della vita familiare. Il datore di lavoro è obbligato a comunicare all'INPS l'istaurarsi di tale rapporto di lavoro, prima della data di assunzione, così come qualsiasi modifica dei termini del rapporto stesso ovvero la sua cessazione. In virtù di tale comunicazione, al rapporto di lavoro viene assegnato da INPS un codice identificativo utile per qualsiasi successivo adempimento inerente al rapporto stesso.
   La metadatazione semantica degli schemi si basa sul documento
   [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    LavoratoreDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico"
    ContrattoLavoro:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro/contratto-di-lavoro.oas3.yaml#/components/schemas/ContrattoLavoro"
    DatoreDiLavoroDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico"
    IdRapportoLavoroDomestico:
      type: string
      description:
        Codice relativo al Rapporto Di Lavoro Domestico assegnato da INPS al momento della registrazione del relativo contratto ed è finalizzato all'individuazione univoca di ogni record dell'entità. Associato a https://w3id.org/italia/onto/OP21/codiceRapportoDiLavoro.
      example: '789431'
      maxLength: 50
      minLength: 1

    RapportoLavoroDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/onto/OP21/RapportoLavoroDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/onto/OP21/"
        codice_rapporto_lavoro: codiceRapportoDiLavoro
        data_deposito_contratto: dataDepositoContratto
        ha_lavoratore_domestico:
          "@id": haLavoratoreDomestico
        ha_datore_di_lavoro:
          "@id": haDatoreDiLavoro
        originato_da:
          "@id": èOriginatoda
      additionalProperties: true
      description:
         Questo schema rappresenta un rapporto di lavoro tra un datore di lavoro e un lavoratore subordinato che presta servizi di carattere domestico diretti al funzionamento della vita familiare.
         Associato ad https://w3id.org/italia/onto/OP21/RapportoDiLavoroDomestico.
      required:
      - codice_rapporto_lavoro
      properties:
        codice_rapporto_lavoro:
          $ref: "#/components/schemas/IdRapportoLavoroDomestico"
        data_deposito_contratto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        ha_lavoratore_domestico:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        originato_da:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro: '789431'
        data_deposito_contratto: '2023-02-16'
        ha_lavoratore_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        originato_da:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro/contratto-di-lavoro.oas3.yaml#/components/schemas/ContrattoLavoro/example"