openapi: 3.0.3
info:
  title: Schema del Rapporto di Lavoro Domestico
  version: 202401.18.00
  x-summary: Schema del Rapporto di Lavoro Domestico compatibile con l'Ontologia INPS relativa ai contributi previdenziali.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomestico
paths: {}
servers: []
tags: []
components:
  schemas:
    LavoratoreDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico"
    ContrattoLavoro:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico"
    DatoreDiLavoroDomestico:
      $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico"

    IdRapportoLavoroDomestico:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      description: https://w3id.org/italia/social-security/onto/contributions/codiceRapportoDiLavoro
      example: '789431'
      maxLength: 50
      minLength: 1

    RapportoLavoroDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/contributions/"
        data_firma_contratto: dataFirmaContratto
        ha_lavoratore_domestico:
          "@id": haLavoratoreDomestico
        ha_datore_di_lavoro_domestico:
          "@id": haDatoreDiLavoroDomestico
        ha_contratto_di_lavoro_domestico:
          "@id": haContrattoDiLavoroDomestico
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/contributions/RapportoDiLavoroDomestico
      required:
      - codice_rapporto_lavoro
      - data_firma_contratto
      properties:
        codice_rapporto_lavoro:
          $ref: "#/components/schemas/IdRapportoLavoroDomestico"
        data_firma_contratto:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        ha_lavoratore_domestico:
          type: object
          items:
            $ref: "#/components/schemas/LavoratoreDomestico"
        ha_datore_di_lavoro_domestico:
          type: object
          items:
            $ref: "#/components/schemas/DatoreDiLavoroDomestico"
        ha_contratto_di_lavoro_domestico:
          type: object
          items:
            $ref: "#/components/schemas/ContrattoLavoro"
      example:
        codice_rapporto_lavoro:
          $ref: "#/components/schemas/IdRapportoLavoroDomestico/example"
        data_firma_contratto: '2023-02-16'
        ha_lavoratore_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/lavoratore-domestico/latest/lavoratore-domestico.oas3.yaml#/components/schemas/LavoratoreDomestico/example"
        ha_datore_di_lavoro_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/datore-di-lavoro-domestico/latest/datore-di-lavoro-domestico.oas3.yaml#/components/schemas/DatoreDiLavoroDomestico/example"
        ha_contratto_di_lavoro_domestico:
          $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/contratto-di-lavoro-domestico/latest/contratto-di-lavoro-domestico.oas3.yaml#/components/schemas/ContrattoLavoroDomestico/example"
