openapi: 3.0.3
info:
  title: Schema del Lavoratore Domestico
  version: 202401.18.00
  x-summary: Schema del Lavoratore Domestico compatibile con l'Ontologia INPS relativa ai contributi previdenziali.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   https://w3id.org/italia/social-security/onto/contributions/LavoratoreDomestico
paths: {}
servers: []
tags: []
components:
  schemas:

    IdLavoratoreDomestico:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/contributions/identificatoreLavoratoreDomestico
      description: https://w3id.org/italia/social-security/onto/contributions/identificatoreLavoratoreDomestico
      example: '216879'
      maxLength: 50
      minLength: 1

    LavoratoreDomestico:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/contributions/LavoratoreDomestico
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/contributions/"
        retribuzione_oraria_effettiva: retribuzioneOrariaEffettiva
      additionalProperties: true
      description: https://w3id.org/italia/social-security/onto/contributions/LavoratoreDomestico
      required:
      - id_lavoratore_domestico
      - retribuzione_oraria_effettiva
      properties:
        id_lavoratore_domestico:
          $ref: "#/components/schemas/IdLavoratoreDomestico"
        retribuzione_oraria_effettiva:
          type: number
          format: double
      example:
        id_lavoratore_domestico:
          $ref: "#/components/schemas/IdLavoratoreDomestico/example"
        retribuzione_oraria_effettiva: 9.85