openapi: 3.0.3
info:
  title: Schema dell'Esito del Pagamento
  version: 202401.18.00
  x-summary: Schema dell'Esito di un Pagamento compatibile con l'Ontologia INPS relativa a servizi che rivestono uno stesso ruolo nell'ambito di diversi processi produttivi dell'Istituto.
  license:
    name: CC BY 4.0
    url: https://creativecommons.org/licenses/by/4.0/
  termsOfService: https://creativecommons.org/licenses/by/4.0/
  contact:
    name: Andrea Cigliano
    email: andrea.cigliano@inps.it
  description: |-
   Esprime l'esito dell'unico pagamento a cui è associato. È caratterizzato da un identificativo e da una o più descrizioni. L'esito di un pagamento può non essere immediatamente noto poichè l'esecuzione del pagamento può coinvolgere diversi intermediari che potrebbero non comunicare in tempo reale l'effettivo buon fine dell'operazione a loro carico. Quindi a meno di un insuccesso immediato l'esito positivo è confermato salvo buon fine ovvero in attesa di conferma da parte dei PSP coinvolti. In questo senso la classe, potendo evolvere nel tempo, riferisce una sequenza di eventi (al più due) ciascuno associato ad un intervallo temporale di validità.
   La metadatazione semantica degli schemi si basa sul documento [REST API Linked Data keywords](https://www.ietf.org/archive/id/draft-polli-restapi-ld-keywords-00.html)
   che introduce le keyword x-jsonld-type e x-jsonld-context.
paths: {}
servers: []
tags: []
components:
  schemas:
    OrdinePagamento:
     $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/ordine-pagamento/latest/ordine-pagamento.oas3.yaml#/components/schemas/OrdinePagamento"

    IdEsitoPagamento:
      type: string
      x-refersTo: https://w3id.org/italia/social-security/onto/services/identificatoreEsitoPagamento
      description:
        Campo tecnico finalizzato all'individuazione univoca di ogni record dell'entità.
        Associato a https://w3id.org/italia/social-security/onto/services/identificatoreEsitoPagamento.
      example: '12345'
      maxLength: 50
      minLength: 1

    EsitoPagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/EsitoPagamento
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        descrizione_esito_pagamento: descrizioneEsitoPagamento
        riferisce_pagamento:
          "@id": riferiscePagamento
      additionalProperties: true
      description:
          Questo schema rappresenta l'Esito di un pagamento ed è associato a https://w3id.org/italia/social-security/onto/services/EsitoPagamento.
      required:
      - codice_esito_pagamento
      - descrizione_esito_pagamento
      properties:
        codice_esito_pagamento:
          $ref: "#/components/schemas/IdEsitoPagamento"
        descrizione_esito_pagamento:
          type: string
          maxLength: 250
        riferisce_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/Pagamento"
      example:
        codice_esito_pagamento:
          $ref: "#/components/schemas/IdEsitoPagamento/example"
        descrizione_esito_pagamento: 'Positivo'
        riferisce_pagamento:
          $ref: "#/components/schemas/Pagamento/example"

    Pagamento:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/Pagamento
      # This custom property defines the associated json-ld
      #   context that can be used to semantically describe
      #   the instances.
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        importo_pagamento: importoPagamento
        data_pagamento: dataPagamento
        ha_notifica_pagamento:
          "@id": haNotificaDiPagamento
        attiva_ordine_pagamento:
          "@id": attivaOrdineDiPagamento
      additionalProperties: true
      description:
         Questo schema rappresenta un pagamento, ovvero il trasferimento di una somma di denaro come corrispettivo di una prestazione o come mezzo di estinzione di un'obbligazione.
         Lo schema è associato a https://w3id.org/italia/social-security/onto/services/Pagamento.
      required:
      - importo_pagamento
      - data_pagamento
      properties:
        importo_pagamento:
          type: number
          format: double
        data_pagamento:
          type: string
          format: date
          pattern: ([0-9]{4})-([0-1][0-9])-([0-3][0-9])
        ha_notifica_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/BollettinoMav"
        attiva_ordine_pagamento:
          type: object
          items:
            $ref: "#/components/schemas/OrdinePagamento"
      example:
        importo_pagamento: 500.50
        data_pagamento: '2022-06-25'
        ha_notifica_pagamento:
          $ref: "#/components/schemas/BollettinoMav/example"
        attiva_ordine_pagamento:
           $ref: "https://raw.githubusercontent.com/INPS-it/NDC/main/assets/schemas/ordine-pagamento/latest/ordine-pagamento.oas3.yaml#/components/schemas/OrdinePagamento/example"

    BollettinoMav:
      type: object
      x-jsonld-type: https://w3id.org/italia/social-security/onto/services/BollettinoMAV
      x-jsonld-context:
        "@vocab": "https://w3id.org/italia/social-security/onto/services/"
        codice_mav: codiceMAV
      additionalProperties: true
      description:
          Questo schema rappresenta il bollettino MAV (Pagamento Mediante Avviso), ovvero un bollettino il cui pagamento segue una procedura interbancaria standard e che contiene le informazioni necessarie alla banca del creditore e al creditore stesso per la riconciliazione del pagamento.
          Lo schema è associato a https://w3id.org/italia/social-security/onto/services/BollettinoMAV.
      required:
      - codice_mav
      properties:
        codice_mav:
          type: integer
          format: int64
      example:
        codice_mav: 01234567890123456
